/**hippity hoppity what is this fuckery*/
$('#first').click(function(){
	$('.aftermath').show(2000);
	$('#first').css("display","none");
	$('#second').css("display","inline");
})
$('#second').click(function(){
	$('.judgementday').show(2000);
	$('#second').css("display","none");
	$('#third').css("display","inline");
})
$('#third').click(function(){
	$('.armageddon').show(2000);
	$('#third').css("display","none");
	$('#fourth').css("display","inline");
})
/**timed animation from here on out*/
$('#fourth').click(function(){
	$('.ragnarok').show(2000);
	$('.normal').hide("fast");
	$('#fourth').css("display","none");
	setTimeout(function(){
		$('.gosh').show();},1000);
	setTimeout(function(){
		$('.putain').show();},2000);
	setTimeout(function(){
		$('.schibe').show();},2900);
	setTimeout(function(){
		$('.merde').show();},2800);
	setTimeout(function(){
		$('.made').show();},2850);
	setTimeout(function(){
		$('#fifth').css("display","inline");},3500);
	})
$('#fifth').click(function(){
	$('.munch').show();
	$('.convbox').hide();
	$('#fifth').hide();
	$('.kathy').hide();
	$('.bg').hide();
	setTimeout(function(){
		$('.munch').hide();},2000);
	setTimeout(function(){
		$('.gibberish').show();},3000);
	setTimeout(function(){
		$('body').css("background-color","red");},3000);
	setTimeout(function(){
		$('html, body').animate({scrollTop:$(document).height()}, 'slow');},3000);
	setTimeout(function(){
		$('.repeat').show();},4000);
	setTimeout(function(){
		$('.afterthought').show();},6000);
	setTimeout(function(){
		$('.finishing').show();},10000);
})

